name       : mangohud
version    : 0.6.6.1
release    : 7
source     :
    - https://github.com/flightlessmango/MangoHud/releases/download/v0.6.6-1/MangoHud-v0.6.6-1-Source.tar.xz : d0e9c8ec6a2c19684edcf7e9fe015244326a783053c4a6c2782ee1792c6bf257
license    : MIT
component  : system.utils
summary    : Vulkan overlay layer for monitoring FPS, temperatures, CPU/GPU load and more
description: |
    A modification of the Mesa Vulkan overlay. Including GUI improvements, temperature reporting, and logging capabilities.
emul32     : yes
libsplit   : no
patterns   :
    - /*
builddeps  :
    - pkgconfig32(libdrm)
    - pkgconfig32(vulkan)
    - pkgconfig32(x11)
    - pkgconfig(glew)
    - pkgconfig(glfw3)
    - glslang-devel
    - mako
    - vulkan-headers
setup      : |
    %meson_configure -Dmangoapp=true -Duse_system_vulkan=enabled -Dwith_xnvctrl=disabled
build      : |
    %ninja_build
install    : |
    %ninja_install
    # Install default configuration file
    install -Dm00644 $workdir/bin/MangoHud.conf -t $installdir/usr/share/mangohud

