name       : mangohud
version    : 0.6.7
release    : 9
source     :
    - https://github.com/flightlessmango/MangoHud/releases/download/v0.6.7/MangoHud-v0.6.7-Source.tar.xz : 6d24b8b2cbd83e1ca8d9956e5cb3f7345c5208c66524f2e229f11df437255214
license    : MIT
component  : system.utils
summary    : Vulkan overlay layer for monitoring FPS, temperatures, CPU/GPU load and more
description: |
    A modification of the Mesa Vulkan overlay. Including GUI improvements, temperature reporting, and logging capabilities.
emul32     : yes
libsplit   : no
patterns   :
    - /*
builddeps  :
    - pkgconfig32(libdrm)
    - pkgconfig(nlohmann_json)
    - pkgconfig32(vulkan)
    - pkgconfig32(x11)
    - pkgconfig(glew)
    - pkgconfig(glfw3)
    - glslang-devel
    - mako
    - vulkan-headers
setup      : |
    %patch -p1 < $pkgfiles/0001-Use-system-nlohmann-json.patch
    %meson_configure -Dmangoapp=true -Duse_system_vulkan=enabled -Dwith_xnvctrl=disabled
build      : |
    %ninja_build
install    : |
    %ninja_install
    # Install default configuration file
    install -Dm00644 $workdir/bin/MangoHud.conf -t $installdir/usr/share/mangohud

