name       : mangohud
version    : 0.6.8
release    : 11
source     :
    - https://github.com/flightlessmango/MangoHud/releases/download/v0.6.8/MangoHud-v0.6.8-Source.tar.xz : 9c64ccab1a72ba1dc61cb88d2fbcce1d343fc6b6cdf22c2cc2859bfb2da66fd4
license    : MIT
component  : system.utils
summary    : Vulkan overlay layer for monitoring FPS, temperatures, CPU/GPU load and more
description: |
    A modification of the Mesa Vulkan overlay. Including GUI improvements, temperature reporting, and logging capabilities.
emul32     : yes
libsplit   : no
patterns   :
    - /*
builddeps  :
    - pkgconfig32(libdrm)
    - pkgconfig32(vulkan)
    - pkgconfig32(x11)
    - pkgconfig(glew)
    - pkgconfig(glfw3)
    - pkgconfig(nlohmann_json)
    - glslang-devel
    - mako
    - vulkan-headers
setup      : |
    %meson_configure -Dmangoapp=true -Dinclude_doc=true -Duse_system_vulkan=enabled -Dwith_xnvctrl=disabled
build      : |
    %ninja_build
install    : |
    %ninja_install
    install -Dm00644 $workdir/data/MangoHud.conf -t $installdir/usr/share/mangohud
